# Numpy Arrays

In [2]:
# Importanto la libreria
import numpy as np

In [3]:
# Arreglo de enteros:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
# Arreglo de flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
# ARreglo de flotantes forzado por el tipo 
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# Arreglo bidimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
# Arreglo de 10 ceros de tipo entro
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Arreglo de 10 ceros de tipo entro
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Matriz de 1's flotantes de 3x5
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.ones((3,4,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [13]:
np.zeros((4,4,4,4,4), dtype=int)

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]],


        [[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]],

         [[0, 0,

In [14]:
# Matriz de 3x5 inicializada con 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
np.full((4,6), 17)

array([[17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17, 17]])

In [16]:
# Array inicia en 0 y termina uno antes de 20 sumando de 2 en 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(7,26,2)

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [17]:
# ARray de 5 valores entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [19]:
# ARray de 11 valores entre 0 y 10
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
# Matriz de 3x3 creada con numeros aleatorios con distribucion uniforme
np.random.random((3, 3))

array([[0.23535389, 0.78428371, 0.2404634 ],
       [0.25318299, 0.71913891, 0.18336335],
       [0.10988148, 0.7862434 , 0.27260066]])

In [23]:
np.random.random((3,3,3))

array([[[0.5011433 , 0.64206738, 0.23366297],
        [0.34934165, 0.8532079 , 0.65831575],
        [0.3179249 , 0.98646025, 0.48607725]],

       [[0.96406481, 0.38548185, 0.42382745],
        [0.70587341, 0.53018373, 0.0449516 ],
        [0.31651991, 0.93220945, 0.34813636]],

       [[0.08056566, 0.55392991, 0.29631453],
        [0.47877597, 0.97846687, 0.16048042],
        [0.75258133, 0.21621869, 0.42128862]]])

In [24]:
# Matriz de 3x3 de numeros aleatorios con distribucion normal
np.random.normal(0, 1, (3, 3))

array([[ 0.05987063,  0.01167843, -0.88388056],
       [-0.45078563, -1.12201037, -1.07463938],
       [-1.09728048, -0.44396903, -0.68169447]])

In [25]:
# Matriz de 3x3 de numeros enteros aleatorios entre 0 y 10 con distribucion uniforme
np.random.randint(0, 100, (3, 3))

array([[52, 26, 25],
       [30, 68, 37],
       [84, 48, 92]], dtype=int32)

In [26]:
# Matriz identidad de 5x5
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# Arreglo de tres valores vacios.
# EL valor mostrado es lo que se encuentre en esa memoria
np.empty(3)

array([9.92876973e-312, 0.00000000e+000, 7.30390958e-311])