# Agregacion de elementos a un array

In [1]:
import numpy as np

In [11]:
# Tensor de una dimension con 3 elementos con valores enteros igual a 1 
array1 = np.ones(3, dtype='int16')
array1

array([1, 1, 1], dtype=int16)

In [12]:
# Tensor de una dimension con 3 elementos con valores enteros iguales a 0
array2 = np.zeros(3, dtype='int16')
array2

array([0, 0, 0], dtype=int16)

In [13]:
# Lista con 2 elementos que son arreglos d eNumpy
array3 = [array1, array2]
print(array3)

[array([1, 1, 1], dtype=int16), array([0, 0, 0], dtype=int16)]


In [14]:
array4 = np.append(array1, array2)
array4

array([1, 1, 1, 0, 0, 0], dtype=int16)

In [17]:
array5= np.random.random(3)
array5

array([0.93266385, 0.78610828, 0.54058492])

In [19]:
array6 = np.append(array1, array5)
array6

array([1.        , 1.        , 1.        , 0.93266385, 0.78610828,
       0.54058492])

In [20]:
array7 = np.array(['a','b', 'c'])
array7

array(['a', 'b', 'c'], dtype='<U1')

In [22]:
array8 = np.append(array5, array7)
array8

array(['0.9326638500291797', '0.7861082759846578', '0.5405849159520748',
       'a', 'b', 'c'], dtype='<U32')

In [25]:
float(array8[0])+float(array8[1])

1.7187721260138376

In [26]:
array8[0]+array8[1]

'0.93266385002917970.7861082759846578'

In [27]:
array1

array([1, 1, 1], dtype=int16)

In [28]:
array2

array([0, 0, 0], dtype=int16)

In [29]:
array11 = array1.reshape(1,3)
array11

array([[1, 1, 1]], dtype=int16)

In [30]:
array22 = array2.reshape(1,3)
array22

array([[0, 0, 0]], dtype=int16)

In [31]:
array33 = np.append(array11, array22)
array33

array([1, 1, 1, 0, 0, 0], dtype=int16)

In [32]:
array44 = np.append(array11, array22, axis=0)
array44

array([[1, 1, 1],
       [0, 0, 0]], dtype=int16)

In [34]:
array55 = np.append(array1, array2, axis=1)
array55

AxisError: axis 1 is out of bounds for array of dimension 1

In [35]:
prueba1 = np.arange(1,13).reshape(3,4)
prueba1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
prueba2 = np.random.normal(0,1,4).reshape(1,4)
prueba2

array([[1.05139233, 0.24806555, 0.47002908, 1.37472574]])

In [37]:
prueba3 = np.append(prueba1, prueba2)
prueba3

array([ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
        6.        ,  7.        ,  8.        ,  9.        , 10.        ,
       11.        , 12.        ,  1.05139233,  0.24806555,  0.47002908,
        1.37472574])

In [38]:
prueba4 = np.append(prueba1, prueba2, axis=0)
prueba4

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [ 9.        , 10.        , 11.        , 12.        ],
       [ 1.05139233,  0.24806555,  0.47002908,  1.37472574]])

In [39]:
prueba5 = np.random.normal(100,2,12).reshape(3,4)
prueba5

array([[100.47537423, 100.60042872,  97.53273467, 102.5876139 ],
       [104.12186057, 102.01034916,  98.14960432,  98.50858529],
       [ 97.17481143,  93.55459789, 101.53134997,  98.35111657]])

In [41]:
prueba6= np.append(prueba1, prueba5)
prueba6

array([  1.        ,   2.        ,   3.        ,   4.        ,
         5.        ,   6.        ,   7.        ,   8.        ,
         9.        ,  10.        ,  11.        ,  12.        ,
       100.47537423, 100.60042872,  97.53273467, 102.5876139 ,
       104.12186057, 102.01034916,  98.14960432,  98.50858529,
        97.17481143,  93.55459789, 101.53134997,  98.35111657])

In [42]:
prueba7= np.append(prueba1, prueba5, axis=0)
prueba7

array([[  1.        ,   2.        ,   3.        ,   4.        ],
       [  5.        ,   6.        ,   7.        ,   8.        ],
       [  9.        ,  10.        ,  11.        ,  12.        ],
       [100.47537423, 100.60042872,  97.53273467, 102.5876139 ],
       [104.12186057, 102.01034916,  98.14960432,  98.50858529],
       [ 97.17481143,  93.55459789, 101.53134997,  98.35111657]])