# Formas de los arreglos
## Esto es un subtitulo
### Esto es un sub sub titulo

In [1]:
import numpy as np

In [4]:
# Tensor de una dimension  con 16 elementos aleatorios
aletorios = np.random.randint(0, 100, size=(16))
aletorios

array([59, 22, 78,  7, 50, 72, 21, 44, 67,  3, 73, 26, 38, 25, 77, 94],
      dtype=int32)

In [5]:
# Tensor de 2 dimensiones y 4 elementos por dimension
aletorios2 = np.random.randint(0, 100, size=(4,4))
aletorios2

array([[61, 72, 13, 44],
       [11,  5, 24, 82],
       [ 3, 18, 99, 19],
       [56, 72, 50, 68]], dtype=int32)

In [6]:
# Reformatear el tensor de una dimension en un tensor de dos dimensiones con 4 renglones y 4 columnas
aleatorios3 = aletorios.reshape(4,4)
aleatorios3

array([[59, 22, 78,  7],
       [50, 72, 21, 44],
       [67,  3, 73, 26],
       [38, 25, 77, 94]], dtype=int32)

In [7]:
# COnvertir el tensor unidimensional en un tensor de dos dimensiones con 2 renglones y 8 columnas
aleatorios4 = aletorios.reshape(2,8)
aleatorios4

array([[59, 22, 78,  7, 50, 72, 21, 44],
       [67,  3, 73, 26, 38, 25, 77, 94]], dtype=int32)

In [8]:
# Convertir el tensor de una dimension en un tensor de dos dimensiones con 3 renglones y 4 columnas

aleatorios5 = aletorios.reshape(3,4)
aleatorios5

ValueError: cannot reshape array of size 16 into shape (3,4)