# Slicing de arreglos

In [1]:
import numpy as np

In [3]:
matriz = np.random.randint(0, 100, size=(10,10))
matriz

array([[29, 97, 81, 11, 89, 50, 64, 55, 95, 35],
       [36, 98, 81, 61, 80, 82, 62, 49, 64, 32],
       [75, 31,  9, 81, 92,  1,  7, 34, 13,  3],
       [45, 94, 13,  3, 72,  9, 41,  3, 66, 40],
       [34, 68, 64, 51, 95, 69, 26, 56, 91,  9],
       [35, 44, 82, 77, 35, 25,  2, 97, 26, 55],
       [71, 36, 96, 10, 48, 22, 41, 85, 74, 14],
       [81,  7, 42,  0, 41, 38,  1, 97, 91, 24],
       [30, 74, 72, 14, 22, 79, 20, 91, 74, 67],
       [76, 61, 33,  7, 67, 69, 36, 72, 37, 37]], dtype=int32)

In [16]:
# Columnas pares, renglones impares
subMatriz = matriz[1::2, 0::2]
subMatriz

array([[36, 81, 80, 62, 64],
       [45, 13, 72, 41, 66],
       [35, 82, 35,  2, 26],
       [81, 42, 41,  1, 91],
       [76, 33, 67, 36, 37]], dtype=int32)

In [17]:
subMatriz[0, 0] = -1
subMatriz

array([[-1, 81, 80, 62, 64],
       [45, 13, 72, 41, 66],
       [35, 82, 35,  2, 26],
       [81, 42, 41,  1, 91],
       [76, 33, 67, 36, 37]], dtype=int32)

In [23]:
matriz

array([[29, 97, 81, 11, 89, 50, 64, 55, 95, 35],
       [-1, 98, 81, 61, 80, 82, 62, 49, 64, 32],
       [75, 31,  9, 81, 92,  1,  7, 34, 13,  3],
       [45, 94, 13,  3, 72,  9, 41,  3, 66, 40],
       [34, 68, 64, 51, 95, 69, 26, 56, 91,  9],
       [35, 44, 82, 77, 35, 25,  2, 97, 26, 55],
       [71, 36, 96, 10, 48, 22, 41, 85, 74, 14],
       [81,  7, 42,  0, 41, 38,  1, 97, 91, 24],
       [30, 74, 72, 14, 22, 79, 20, 91, 74, 67],
       [76, 61, 33,  7, 67, 69, 36, 72, 37, 37]], dtype=int32)

In [ ]:
# Renlones del 3 al 6, columnas de 3 al 6. Invertir renglones y columnas
# Esto devuelve un arreglo vacio, porque el elemento final de las columnas
# esta por delante del elemento inicial y el incremento es positivo
# Esto no imprime un error, simplemente imprime un arreglo vacio
matriz[-4:2:-1, -4:2:]


In [25]:
# Renlones del 3 al 6, columnas de 3 al 6. Invertir renglones 
matriz[-4:2:-1, 3:7:]

array([[10, 48, 22, 41],
       [77, 35, 25,  2],
       [51, 95, 69, 26],
       [ 3, 72,  9, 41]], dtype=int32)

In [21]:
# Renlones del 3 al 6, columnas de 3 al 6. Invertir renglones y columnas
matriz[-4:2:-1, -4:2:-1]

array([[41, 22, 48, 10],
       [ 2, 25, 35, 77],
       [26, 69, 95, 51],
       [41,  9, 72,  3]], dtype=int32)

In [19]:
# Renglones multiplos de 3 y columnas multiplos de 4
matriz[::3, ::4]

array([[29, 89, 95],
       [45, 72, 66],
       [71, 48, 74],
       [76, 67, 37]], dtype=int32)

In [13]:
# Columnas 5 y 6
matriz[:, 5:7]

array([[50, 64],
       [82, 62],
       [ 1,  7],
       [ 9, 41],
       [69, 26],
       [25,  2],
       [22, 41],
       [38,  1],
       [79, 20],
       [69, 36]], dtype=int32)

In [12]:
# La ultima columna
matriz[:, -1:]

array([[35],
       [32],
       [ 3],
       [40],
       [ 9],
       [55],
       [14],
       [24],
       [67],
       [37]], dtype=int32)

In [4]:
print(matriz[5,6])

2


In [11]:
# Renglones pares
matriz[::2, :]

array([[29, 97, 81, 11, 89, 50, 64, 55, 95, 35],
       [75, 31,  9, 81, 92,  1,  7, 34, 13,  3],
       [34, 68, 64, 51, 95, 69, 26, 56, 91,  9],
       [71, 36, 96, 10, 48, 22, 41, 85, 74, 14],
       [30, 74, 72, 14, 22, 79, 20, 91, 74, 67]], dtype=int32)

In [10]:
# Renglones impares
matriz[1::2, :]

array([[36, 98, 81, 61, 80, 82, 62, 49, 64, 32],
       [45, 94, 13,  3, 72,  9, 41,  3, 66, 40],
       [35, 44, 82, 77, 35, 25,  2, 97, 26, 55],
       [81,  7, 42,  0, 41, 38,  1, 97, 91, 24],
       [76, 61, 33,  7, 67, 69, 36, 72, 37, 37]], dtype=int32)

In [9]:
# Los ultimos 4 renglones
matriz[-4:, :]

array([[71, 36, 96, 10, 48, 22, 41, 85, 74, 14],
       [81,  7, 42,  0, 41, 38,  1, 97, 91, 24],
       [30, 74, 72, 14, 22, 79, 20, 91, 74, 67],
       [76, 61, 33,  7, 67, 69, 36, 72, 37, 37]], dtype=int32)

In [8]:
# Los ultimos 4 renglones 
matriz[6:, :]

array([[71, 36, 96, 10, 48, 22, 41, 85, 74, 14],
       [81,  7, 42,  0, 41, 38,  1, 97, 91, 24],
       [30, 74, 72, 14, 22, 79, 20, 91, 74, 67],
       [76, 61, 33,  7, 67, 69, 36, 72, 37, 37]], dtype=int32)

In [5]:
# Los primeros 3 renglones
matriz[0:3, :]

array([[29, 97, 81, 11, 89, 50, 64, 55, 95, 35],
       [36, 98, 81, 61, 80, 82, 62, 49, 64, 32],
       [75, 31,  9, 81, 92,  1,  7, 34, 13,  3]], dtype=int32)