# Intercambio de columnas

In [1]:
import numpy as np

In [3]:
# Tensor de 2 dimenasiones con 4 renglones y 4 columnas
aleatorios = np.arange(1,17).reshape(4,4)
aleatorios

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
# Intercamcio de las columnas 1 y 3
aleatorios[:, [1,3]] = aleatorios[:, [3,1]]
aleatorios

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
# Intercambio de los renglones 0 y 3
aleatorios[[0,3], :] = aleatorios[[3,0], :]
aleatorios

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
aleatorios[1,1], aleatorios[3,3] = aleatorios[3,3], aleatorios[1,1]
aleatorios

array([[ 1,  2,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  6]])

In [4]:
a = 4
b = 5
print(a,b)

4 5


In [5]:
a, b = b,a
print(a,b)

5 4


In [6]:
np.__version__

'2.1.2'