 # Funciones basicas con Arrays

In [1]:
# Importanto la libreria
import numpy as np

In [2]:
# Creamos la semilla par al ageneracion de los numeros aleatorios
np.random.seed(0)  

In [3]:
# x1 es un arreglo unidimensional o un tensor de una dimension
x1 = np.random.randint(10, size=6)  

In [5]:
print(x1)

[5 0 3 3 7 9]


In [6]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [7]:
# Tensor de dos dimensiones
x2 = np.random.randint(10, size=(3, 4))

In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [10]:
x2[0,3]

np.int32(4)

In [11]:
y = np.random.randint(100, 200, (2,3))
y

array([[146, 188, 181],
       [137, 125, 177]], dtype=int32)

In [12]:
# Tensor de 3 dimensiones
x3 = np.random.randint(10, size=(3, 4, 5))

In [13]:
x3

array([[[8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3],
        [8, 1, 3, 3, 3],
        [7, 0, 1, 9, 9]],

       [[0, 4, 7, 3, 2],
        [7, 2, 0, 0, 4],
        [5, 5, 6, 8, 4],
        [1, 4, 9, 8, 1]],

       [[1, 7, 9, 9, 3],
        [6, 7, 2, 0, 3],
        [5, 9, 4, 4, 6],
        [4, 4, 3, 4, 4]]], dtype=int32)

In [15]:
print(x3[1, 2, 3])

8


In [16]:
#Imprimir atributos del tensor x1
print(f'X1 Dim:{x1.ndim} Shape:{x1.shape} Size:{x1.size}')

X1 Dim:1 Shape:(6,) Size:6


In [17]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [18]:
# Imprimir atributos del tensor x2
print(f'X2 Dim:{x2.ndim} Shape:{x2.shape} Size:{x2.size}')

X2 Dim:2 Shape:(3, 4) Size:12


In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [20]:
# Imprimir atributos del tensor x3
print(f'X3 Dim:{x3.ndim} Shape:{x3.shape} Size:{x3.size}')

X3 Dim:3 Shape:(3, 4, 5) Size:60


In [21]:
x3

array([[[8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3],
        [8, 1, 3, 3, 3],
        [7, 0, 1, 9, 9]],

       [[0, 4, 7, 3, 2],
        [7, 2, 0, 0, 4],
        [5, 5, 6, 8, 4],
        [1, 4, 9, 8, 1]],

       [[1, 7, 9, 9, 3],
        [6, 7, 2, 0, 3],
        [5, 9, 4, 4, 6],
        [4, 4, 3, 4, 4]]], dtype=int32)